fastlane_require 'dotenv'

default_platform(:ios)

platform :ios do

  before_all do
    Dotenv.overload '.env'
  end
  
  desc "Build and Deploy app"
  lane :release_app do
    build_app
    deploy_app
  end
  
  desc "Build app"
  lane :build_app do
    gym(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      clean: true,
      export_xcargs: "-allowProvisioningUpdates",
      output_name: "boiler_plate.ipa"
    )
  end

  desc "Deploy app using api key"
  lane :deploy_app do
    api_key = app_store_connect_api_key(
      key_id: ENV['KEY_ID'],
      issuer_id: ENV['ISSUER_ID'],
      key_content: ENV['KEY_CONTENT'],
      duration: 1200,
      in_house: false
    )
    upload_to_testflight(
      api_key: api_key,
      ipa: "boiler_plate.ipa",
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )
  end
end
